version: '3.3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    volumes:
      - ./web/website:/var/www/html
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: db
      MYSQL_USER: sam
      MYSQL_PASSWORD: changeme
    ports:
      - 8000:3306
    